import { Gelasio, Inter, Schibsted_Grotesk, SUSE } from 'next/font/google';
import './globals.scss';

const gelasio = Gelasio({
    subsets: ['latin'],
    variable: '--font-gelasio',
    weight: '400',
});
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const schibstedGrotesk = Schibsted_Grotesk({
    subsets: ['latin'],
    variable: '--font-schibsted',
});
const suse = SUSE({ subsets: ['latin'], variable: '--font-suse' });

export const metadata = {
    title: 'A u v r a',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html
            lang='en'
            className={`${gelasio.variable} ${inter.variable} ${schibstedGrotesk.variable} ${suse.variable}`}
        >
            <body>{children}</body>
        </html>
    );
}
